### ISSUE TITLE
Getting cannot find Module error while converting my Postman Collection to Loadimpact

### ISSUE THREAD

**Issue by discovery-FarhanQuidwai** [loadimpact/postman-to-loadimpact#3]
![image](https://cloud.githubusercontent.com/assets/20905391/22582971/1aef9082-ea10-11e6-8a99-dc7282701501.png)

Getting above Error while converting my collection ?
 can you please help me out in rectifying this ?

**Comment by discovery-FarhanQuidwai** [comment]
@ppcano can you please help me with this ?

**Comment by ppcano** [comment]
Hi @FarhanQuidwai,

Honestly, I haven't tested the library under Windows. Meanwhile, you could contact support@loadimpact.com and share the postman collection with us.  I will try to convert it on my machine and come back to you.

**Comment by discovery-FarhanQuidwai** [comment]
Yeah @ppcano  i have contacted to support@loadimpact.com . Hopefully i can get some idea about this

**Comment by micsjo** [comment]
Can't reproduce this. Will contact customer and ask for details on nmp, node and win versions.
